version: '3.8'

services:
  vestot:
    build: .
    container_name: luach-vestot
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - vestot-data:/data
    environment:
      - PORT=3000
      - DB_PATH=/data/vestot.db
      - SESSION_SECRET=${SESSION_SECRET}
      - ALLOW_REGISTRATION=false
      - NODE_ENV=production
      - SMTP_HOST=smtp-relay.brevo.com
      - SMTP_PORT=587
      - SMTP_USER=a427c1001@smtp-brevo.com
      - SMTP_PASS=xsmtpsib-3b992bdafc34aab8bf5cb26dbf5facbf8507449dd7e9f157cf27118474c26c1a-mrEpNRuz0JAZ2l9s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=10M
    cap_drop:
      - ALL
    networks:
      - web-proxy

volumes:
  vestot-data:

networks:
  web-proxy:
    external: true
